# Generated by Django 2.1.2 on 2018-11-03 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FactSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.ManyToManyField(to='training.Fact')),
            ],
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('fact_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.FactSet')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficients', models.TextField(blank=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Ruleset')),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('frozen_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebpageFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_answer', models.TextField()),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Fact')),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Webpage')),
            ],
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='testing_pages',
            field=models.ManyToManyField(related_name='testing_runs', to='training.Webpage'),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='training_pages',
            field=models.ManyToManyField(related_name='training_runs', to='training.Webpage'),
        ),
    ]
