# Generated by Django 2.1.2 on 2018-11-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='frozen_html',
            field=models.TextField(blank=True),
        ),
    ]
