# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20181103_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingrun',
            old_name=b'coefficients',
            new_name='final_coefficients',
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='initial_coefficients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainingrun',
            name=b'testing_pages',
            field=models.ManyToManyField(blank=True, related_name='testing_runs', to='training.Webpage'),
        ),
        migrations.AlterField(
            model_name='trainingrun',
            name=b'training_pages',
            field=models.ManyToManyField(blank=True, related_name='training_runs', to='training.Webpage'),
        ),
    ]
