# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import fathom_server.training.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20181111_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='frozen_html_file',
            field=models.FileField(blank=True, upload_to=fathom_server.training.models._frozen_html_upload_to),
        ),
        migrations.AlterField(
            model_name='webpage',
            name=b'url',
            field=models.URLField(unique=True),
        ),
    ]
