# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 02:23
from __future__ import unicode_literals

from django.core.files.base import ContentFile
from django.db import migrations


def port_frozen_html_to_file(apps, schema_editor):
    Webpage = apps.get_model('training', 'Webpage')
    for webpage in Webpage.objects.all():
        webpage.frozen_html_file.save(webpage.url, ContentFile(webpage.frozen_html))


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20181116_0200'),
    ]

    operations = [
        migrations.RunPython(port_frozen_html_to_file)
    ]
