# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20181116_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name=b'frozen_html',
        ),
    ]
