# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_remove_webpage_frozen_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='frozen_html_file',
            new_name='frozen_html',
        ),
    ]
