# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20181116_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='name',
            field=models.CharField(default=b'New Ruleset', max_length=255),
        ),
    ]
