# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_ruleset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='factset',
            name='name',
            field=models.CharField(default=b'New Factset', max_length=255),
        ),
    ]
